mybatis:
  typeAliasesPackage: com.szkingdom.entity
  mapperLocations: classpath:com/szkingdom/mapper/xml/*.xml


spring:
  jackson:
    #返回json 日期格式化
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  datasource:
    url: jdbc:mysql://10.220.1.41:3306/smgjdatabase?useUnicode=true&characterEncoding=UTF-8
    username: root
    password: Jzqh_Smgj1
    driver-class-name: com.mysql.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
  redis:
    host: 10.220.1.41
    port: 6379
    timeout: 10000
    password:
    jedis:
      pool:
        #最大连接数
        max-active: 8
        #最大阻塞等待时间(负数表示没限制)
        max-wait: -1ms
        #最大空闲
        max-idle: 8
        #最小空闲
        min-idle: 0